
name: Azure Bicep

on: workflow_dispatch

env:
    targetEnv: dev

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      # Checkout code
      - uses: actions/checkout@main

      - name: Validate secrets
        run: |
          echo ${{ secrets.AZURE_CLIENT_ID }}
          echo ${{ secrets.AZURE_TENANT_ID }}
          echo ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          echo ${{ secrets.AZURE_RG }}
  
        # Log into Azure
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
  
        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
            scope: 'resource-group/${{ secrets.AZURE_RG }}'
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            resourceGroupName: ${{ secrets.AZURE_RG }}
            template: ./InfrastructureAsCode/main.bicep
            parameters: environment=${{ env.targetEnv }}