name: First Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]

env:
  STEP_VAR: STEP
  MSG: MOO!

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Step one
      run: echo "$STEP_VAR one !!"
    - name: Step two
      run: echo "$STEP_VAR two !!"
      
  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Cowsays
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: '${{ ENV.MSG }}'
        color: 'cyan'